version: '3.8'

services:
 
  api1:
    image: nmatsui/hello-world-api:0.1.1 
      
    ports:
      - 3000:3000
 
   
  api2:
    image: nmatsui/hello-world-api:0.1.1 
      
    ports:
      - 3001:3000
  

  api3:
    image: nmatsui/hello-world-api:0.1.1 
      
    ports:
      - 3002:3000
  
