version: '3.8'

services:

  api1:
    container_name: api1
    build: ./api
    ports:
      - 3000:3000
    environment:
      - MESSAGE=${NOMBRE}
     
     
    depends_on:
      - db
   
  api2:
    container_name: api2
    build: ./api
    ports:
      - 3001:3000
    environment:
      - MESSAGE=${NOMBRE}
     
      
    depends_on:
      - db
  
  api3:
    container_name: api3
    build: ./api
    ports:
      - 3002:3000
    environment:
      - MESSAGE=${NOMBRE}
     
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CONTRA}
      POSTGRES_DB: ${POSTGRES_DB}

     
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

volumes:
  postgres_data:
    driver: local

